### ISSUE TITLE
reproduce results matched figure 5 in paper

### ISSUE THREAD

**Issue by Dxye** [genforce/sefa#10]
Hi, thanks for your great research first. May I have the seed to generate the source StyleGAN image which used in figure 5 of the paper?  And also the index of sorted eigen value corresponding to "Pose", "Eyeglasses" and "Smile" manipulation so that I can reproduce results in figure 5.

By the way, the InterFaceGAN result in qualitative comparison were produced in W space or W+ space?

Thanks.

**Comment by ShenYujun** [comment]
For StyleGAN, pose, eyeglasses, smile are with index 1, 6, 37. Meanwhile, InterFaceGAN is using W space.
