### ISSUE TITLE
About code release schedule

### ISSUE THREAD

**Issue by rlalpha** [genforce/sefa#2]
I found that paper is really innovative.  I want to try building something on top of it.
Can I ask about the estimated released date of the code?

Thank you a lot.

**Comment by ShenYujun** [comment]
We plan to release the code in 2-3 weeks. Please be patient. ;)

**Comment by jimmyrustler** [comment]
I think i got the gist of the paper, it can be summarized as these few lines of code.
```
from sklearn.decomposition import PCA
import torch
z_length = 128
y_length = 64

linear = torch.nn.Linear(z_length, y_length)
gan_model = ...
model = torch.nn.Sequential(linear, gan_model)
#train your model here

pca = PCA(n_components=2)
pca.fit(linear.weight.numpy())

#eigenvectors
print(pca.components_)
#eigenvalues
print(pca.singular_values_)

```

**Comment by SteveVanWang** [comment]
> We plan to release the code in 2-3 weeks. Please be patient. ;)

hope to build some task on top of this code，may I ask when will release the whole code,thanks a lot

**Comment by ShenYujun** [comment]
Thanks for the follow-up! We are sorry for the delay because of the CVPR due and we will release the core code next week!

**Comment by ShenYujun** [comment]
The code is released! Welcome to give it a try ;)

**Comment by dcalsky** [comment]
> The code is released! Welcome to give it a try ;)

Do you willing to share your pre-trained models?

**Comment by ShenYujun** [comment]
The models are released in the [genforce](https://github.com/genforce/genforce) repo and included in this repo as well.
