### ISSUE TITLE
Using a custom model

### ISSUE THREAD

**Issue by YukiSakuma** [genforce/sefa#3]
Hi thanks for the release, I've been waiting for it.
So I have a stylegan2 model converted from tf to pytorch, how would I go about using it?
I am getting a keyerror when loading the converted .pt model

```
Traceback (most recent call last):
  File "sefa.py", line 145, in <module>
    main()
  File "sefa.py", line 70, in main
    generator = load_generator(args.model_name)
  File "J:\sefa-master\utils.py", line 101, in load_generator
    generator.load_state_dict(checkpoint['generator'])
KeyError: 'generator'

```
Printing the keys of my model yields `dict_keys(['g_ema', 'latent_avg'])
` but your pretrained models yield `dict_keys(['generator', 'discriminator', 'generator_smooth'])
`
What should I still need to do? I am able to use a closed-form-factorization implementation using my converted model from this [stylegan2-pytorch repo](https://github.com/rosinality/stylegan2-pytorch) but how to do it in this one?

**Comment by ShenYujun** [comment]
There are two feasible solutions. First, 'g_ema' should align with 'generator_smooth', but it is not guaranteed that your converted weights fit the implementation in `models`. Second, you can check the function `factorize_weight()` in file `utils.py`. The core implementation only requires several lines of codes.

**Comment by YukiSakuma** [comment]
Using `g_ema` outputs blobs. Is there a script that converts the model so that it's compatible with your implementation? I don't really have the know-how in doing it.

**Comment by ShenYujun** [comment]
You can use the [code](https://github.com/genforce/higan/blob/d10eb9edba7ca28f24168ed23ac5bb2f034a88d8/models/stylegan_generator.py#L60) from HiGAN as a reference and make some modifications.

**Comment by YukiSakuma** [comment]
> You can use the [code](https://github.com/genforce/higan/blob/d10eb9edba7ca28f24168ed23ac5bb2f034a88d8/models/stylegan_generator.py#L60) from HiGAN as a reference and make some modifications.

Thanks for the script I did it using `test.py `and was able to convert my tf stylegan2 model to your pytorch one but I'm lost what to do next I thought there was going to be a `generator` key when loading the model but I get these keys

```
mapping.dense0.bias
mapping.dense0.fc.weight
mapping.dense1.bias
mapping.dense1.fc.weight
mapping.dense2.bias
mapping.dense2.fc.weight
mapping.dense3.bias
mapping.dense3.fc.weight
mapping.dense4.bias
mapping.dense4.fc.weight
mapping.dense5.bias
mapping.dense5.fc.weight
mapping.dense6.bias
mapping.dense6.fc.weight
mapping.dense7.bias
mapping.dense7.fc.weight
truncation.w_avg
synthesis.early_layer.const
synthesis.layer0.weight
synthesis.layer0.bias
synthesis.layer0.noise_strength
synthesis.layer0.noise
synthesis.layer0.style.bias
synthesis.layer0.style.fc.weight
synthesis.output0.weight
synthesis.output0.bias
synthesis.output0.style.bias
synthesis.output0.style.fc.weight
synthesis.layer1.weight
synthesis.layer1.bias
synthesis.layer1.noise_strength
synthesis.layer1.noise
synthesis.layer1.filter.kernel
synthesis.layer1.style.bias
synthesis.layer1.style.fc.weight
synthesis.layer2.weight
synthesis.layer2.bias
synthesis.layer2.noise_strength
synthesis.layer2.noise
synthesis.layer2.style.bias
synthesis.layer2.style.fc.weight
synthesis.output1.weight
synthesis.output1.bias
synthesis.output1.style.bias
synthesis.output1.style.fc.weight
synthesis.layer3.weight
synthesis.layer3.bias
synthesis.layer3.noise_strength
synthesis.layer3.noise
synthesis.layer3.filter.kernel
synthesis.layer3.style.bias
synthesis.layer3.style.fc.weight
synthesis.layer4.weight
synthesis.layer4.bias
synthesis.layer4.noise_strength
synthesis.layer4.noise
synthesis.layer4.style.bias
synthesis.layer4.style.fc.weight
synthesis.output2.weight
synthesis.output2.bias
synthesis.output2.style.bias
synthesis.output2.style.fc.weight
synthesis.layer5.weight
synthesis.layer5.bias
synthesis.layer5.noise_strength
synthesis.layer5.noise
synthesis.layer5.filter.kernel
synthesis.layer5.style.bias
synthesis.layer5.style.fc.weight
synthesis.layer6.weight
synthesis.layer6.bias
synthesis.layer6.noise_strength
synthesis.layer6.noise
synthesis.layer6.style.bias
synthesis.layer6.style.fc.weight
synthesis.output3.weight
synthesis.output3.bias
synthesis.output3.style.bias
synthesis.output3.style.fc.weight
synthesis.layer7.weight
synthesis.layer7.bias
synthesis.layer7.noise_strength
synthesis.layer7.noise
synthesis.layer7.filter.kernel
synthesis.layer7.style.bias
synthesis.layer7.style.fc.weight
synthesis.layer8.weight
synthesis.layer8.bias
synthesis.layer8.noise_strength
synthesis.layer8.noise
synthesis.layer8.style.bias
synthesis.layer8.style.fc.weight
synthesis.output4.weight
synthesis.output4.bias
synthesis.output4.style.bias
synthesis.output4.style.fc.weight
synthesis.layer9.weight
synthesis.layer9.bias
synthesis.layer9.noise_strength
synthesis.layer9.noise
synthesis.layer9.filter.kernel
synthesis.layer9.style.bias
synthesis.layer9.style.fc.weight
synthesis.layer10.weight
synthesis.layer10.bias
synthesis.layer10.noise_strength
synthesis.layer10.noise
synthesis.layer10.style.bias
synthesis.layer10.style.fc.weight
synthesis.output5.weight
synthesis.output5.bias
synthesis.output5.style.bias
synthesis.output5.style.fc.weight
synthesis.layer11.weight
synthesis.layer11.bias
synthesis.layer11.noise_strength
synthesis.layer11.noise
synthesis.layer11.filter.kernel
synthesis.layer11.style.bias
synthesis.layer11.style.fc.weight
synthesis.layer12.weight
synthesis.layer12.bias
synthesis.layer12.noise_strength
synthesis.layer12.noise
synthesis.layer12.style.bias
synthesis.layer12.style.fc.weight
synthesis.output6.weight
synthesis.output6.bias
synthesis.output6.style.bias
synthesis.output6.style.fc.weight
synthesis.layer13.weight
synthesis.layer13.bias
synthesis.layer13.noise_strength
synthesis.layer13.noise
synthesis.layer13.filter.kernel
synthesis.layer13.style.bias
synthesis.layer13.style.fc.weight
synthesis.layer14.weight
synthesis.layer14.bias
synthesis.layer14.noise_strength
synthesis.layer14.noise
synthesis.layer14.style.bias
synthesis.layer14.style.fc.weight
synthesis.output7.weight
synthesis.output7.bias
synthesis.output7.style.bias
synthesis.output7.style.fc.weight
synthesis.upsample.kernel
```

**Comment by ShenYujun** [comment]
You can treat the converted model as a whole with something like `new_mode['generator'] = converted_model`.

**Comment by junikkoma** [comment]
Hi. I would first like to thank you about your great work.
I am trying to do same thing as YukiSakuma.

I've noticed YukiSakuma's keys are slightly different from your pth file from MODEL_ZOO
ex) mapping.dense0.fc.weight (higan modification) vs mapping.dense0.weight (pth file of model_zoo)

I am guessing after key modification converted model could be applied to your code

However, I am wondering whether weight loading could be done without key modification.
would it throw exception if I don't modify keys, or would it work fine as is?

**Comment by junikkoma** [comment]
Hi. I first would like to thank you for this great work.

I've noticed YukiSakuma's key's are still quite different from keys from pth file in MODEL_ZOO
ex) mapping.dense0.fc.weight(from modification of higan) vs mapping.dense0.weight(keys from LSUN_CARS @ pth file of MODEL_ZOO)

So I am guessing if I align keys of converted model from this [stylegan2-pytorch repo](https://github.com/rosinality/stylegan2-pytorch) with pth file in MODEL_ZOO, it would work.

I want to ask your opinion about such key alignment. Thanks in advance!

**Comment by ShenYujun** [comment]
Since the implementation is updated compared to HiGAN, it indeed requires some modifications to align the keys. But I believe it should be quiet simple.

**Comment by YukiSakuma** [comment]
Correct me if I'm wrong by modification do you mean just renaming the keys?
For example renaming `mapping.dense0.fc.weight` to `mapping.dense0.weight`. I tried that and the` KeyError: ‘unexpected key'` is gone but still I am getting a size mismatch when loading as `generator.load_state_dict(checkpoint)`
```
# size mismatch for synthesis.layer0.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.output0.weight: copying a param with shape torch.Size([1, 1, 512, 3]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
# 	size mismatch for synthesis.layer1.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.layer2.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.output1.weight: copying a param with shape torch.Size([1, 1, 512, 3]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
# 	size mismatch for synthesis.layer3.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.layer4.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.output2.weight: copying a param with shape torch.Size([1, 1, 512, 3]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
# 	size mismatch for synthesis.layer5.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.layer6.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.output3.weight: copying a param with shape torch.Size([1, 1, 512, 3]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
# 	size mismatch for synthesis.layer7.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.layer8.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
# 	size mismatch for synthesis.output4.weight: copying a param with shape torch.Size([1, 1, 512, 3]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
# 	size mismatch for synthesis.layer9.weight: copying a param with shape torch.Size([3, 3, 512, 256]) from checkpoint, the shape in current model is torch.Size([256, 512, 3, 3]).
# 	size mismatch for synthesis.layer10.weight: copying a param with shape torch.Size([3, 3, 256, 256]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
# 	size mismatch for synthesis.output5.weight: copying a param with shape torch.Size([1, 1, 256, 3]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
# 	size mismatch for synthesis.layer11.weight: copying a param with shape torch.Size([3, 3, 256, 128]) from checkpoint, the shape in current model is torch.Size([128, 256, 3, 3]).
# 	size mismatch for synthesis.layer12.weight: copying a param with shape torch.Size([3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
# 	size mismatch for synthesis.output6.weight: copying a param with shape torch.Size([1, 1, 128, 3]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1]).
# 	size mismatch for synthesis.layer13.weight: copying a param with shape torch.Size([3, 3, 128, 64]) from checkpoint, the shape in current model is torch.Size([64, 128, 3, 3]).
# 	size mismatch for synthesis.layer14.weight: copying a param with shape torch.Size([3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
# 	size mismatch for synthesis.output7.weight: copying a param with shape torch.Size([1, 1, 64, 3]) from checkpoint, the shape in current model is torch.Size([3, 64, 1, 1]).
```

**Comment by junikkoma** [comment]
I think it would be better to manually transpose it.
I did some tedious work converting, and it seems that loading part is fine
```
from models import stylegan2_generator
model = stylegan2_generator.StyleGAN2Generator(512)
import torch
convert = torch.load('CXR.pth')['generator']
model.load_state_dict(convert)
```
where CXR.pth is weight file with key alignment
result for code above is 
```<All keys matched successfully>```

**Comment by YukiSakuma** [comment]
@junikkoma
can you share your code conversion script?

**Comment by YukiSakuma** [comment]
My method so far but it didn't work, is take a TF model convert it to pytorch using from the higan repo then I rename(align the keys) like removing the `.fc` then as for the key size mismatch I made a new state dict by using `var.permute(3,2,1,0)` and after that it loads successfully but the output images are a blob. So can anyone correct me?

**Comment by junikkoma** [comment]
@YukiSakuma I was not responding because my results were blob as well. I guess we are both facing permuatition problems

ex) on 
```
size mismatch for synthesis.layer0.weight: copying a param with shape torch.Size([3, 3, 512, 512]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
```
the correct permutation may be (2,3,0,1 ) instead of (3,2,1,0) as we converted...

**Comment by YukiSakuma** [comment]
@junikkoma interesting but if I use (2,3,0,1 ) I will get back to the size mismatch error.

**Comment by junikkoma** [comment]
my point is that there are more than one permutation that solves size error, and heuristically deciding which permutations to choose may solve bad result issue

**Comment by YukiSakuma** [comment]
While currently it is a blob, the colors is expected what the model would output, and also it kind of looks like it's rotated 90 degrees to the left.

**Comment by YukiSakuma** [comment]
Finally got it use ` val.permute( 3,2,0,1  )` instead

**Comment by junikkoma** [comment]
@YukiSakuma you are getting result you desired? can you share your results?
also, i would really appreciate if you share your conversion code

**Comment by YukiSakuma** [comment]
Here is the code when fixing the size mismatch
```
import torch
from collections import OrderedDict
new_state_dict = OrderedDict()
model = torch.load('MODEL TO BE CONVERTED.PTH')
converted = 'PATH OF CONVERTED.PTH'
check = ['synthesis.layer0.weight', 'synthesis.output0.weight', 'synthesis.layer1.weight', 'synthesis.layer2.weight', 'synthesis.output1.weight', 'synthesis.layer3.weight', 'synthesis.layer4.weight', 'synthesis.output2.weight', 'synthesis.layer5.weight', 'synthesis.layer6.weight', 'synthesis.output3.weight', 'synthesis.layer7.weight', 'synthesis.layer8.weight', 'synthesis.output4.weight', 'synthesis.layer9.weight', 'synthesis.layer10.weight', 'synthesis.output5.weight', 'synthesis.layer11.weight', 'synthesis.layer12.weight', 'synthesis.output6.weight', 'synthesis.layer13.weight', 'synthesis.layer14.weight', 'synthesis.output7.weight']
for key, val in model.items():
    if key in check:
      new_val = val.permute(3, 2, 0, 1)
      new_state_dict[key] = new_val
    else:
      new_state_dict[key] = val

torch.save(new_state_dict, converted)
```
I tested it using the StyleGAN2 anime model available from here https://www.gwern.net/Faces#stylegan-2

![Sefa stylegan2 anime face](https://i.imgur.com/eCbzGMn.png)

**Comment by junikkoma** [comment]
@YukiSakuma I am a bit confused, so check me if I'm right
you first changed your tf weight with code modified from HIGAN conversion,
then you renamed your keys,
and then finally you reshaped some values with ```permute(3,2,0,1)```?

**Comment by YukiSakuma** [comment]
@junikkoma Yes that's about it and it worked, fixing the size mismatch was really the tricky part.

**Comment by junikkoma** [comment]
@YukiSakuma I really appreciate your help. My weights are loaded as well.
I guess [this](https://github.com/genforce/higan/blob/d10eb9edba7ca28f24168ed23ac5bb2f034a88d8/models/stylegan_generator.py#L95) line from higan is problem as it uses same permutation, and in original keys there are no layers that have 'Conv' or 'conv' in it

**Comment by tengolagan** [comment]
> Hi thanks for the release, I've been waiting for it. So I have a stylegan2 model converted from tf to pytorch, how would I go about using it? I am getting a keyerror when loading the converted .pt model
> 
> ```
> Traceback (most recent call last):
>   File "sefa.py", line 145, in <module>
>     main()
>   File "sefa.py", line 70, in main
>     generator = load_generator(args.model_name)
>   File "J:\sefa-master\utils.py", line 101, in load_generator
>     generator.load_state_dict(checkpoint['generator'])
> KeyError: 'generator'
> ```
> 
> Printing the keys of my model yields `dict_keys(['g_ema', 'latent_avg']) ` but your pretrained models yield `dict_keys(['generator', 'discriminator', 'generator_smooth']) ` What should I still need to do? I am able to use a closed-form-factorization implementation using my converted model from this [stylegan2-pytorch repo](https://github.com/rosinality/stylegan2-pytorch) but how to do it in this one?

Hi! Sorry for reopening the issue more than a year after, but I have the same problem. How did you manage to overcome it ? 
Thanks, I would really appreciate your help
