### ISSUE TITLE
About ignore the non-linear layers of the mapping net.

### ISSUE THREAD

**Issue by cnnlstm** [genforce/sefa#8]
Thanks for your excellent work!  but the mapping net consists of 8 FC layers with 'leak_relu' in between. But the code seems to concatenate the weight of each layer as the final weight, but ignores the 'leak_relu' layers. Why ignore them?

**Comment by ShenYujun** [comment]
The mapping network is not used in this work. We use the final output (the disentangled latent code `w`) of these 8 FC layers as the starting point for factorization.

**Comment by cnnlstm** [comment]
Thanks for your reply,  I still have some questions:

As shown in Eq(1) of your paper: 
> G1(z)= y = **A**z + **b**. (1)

for the StyleGAN, here **z** is the gaussian noise and **y** is the disentangled latent code **w**, right? However, since there are _leak_relu_ layers in the mapping net of StyleGAN, the **w** code cannot be transformed by such a linear transformation.  They should be:
> G1(z)= y = LeakRelu(**A**z + **b**). 


As a result, Eq(3) in your paper is not supported, it should be 

> G1(z + αn)= leakRelu(**A**z + **b** + α**A**n) != LeakRelu(**A**z + **b**) + α**A**n != LeakRelu(**A**z + **b**) + LeakRelu(α**A**n)

As a result, _the editing can **not** be always achieved by adding the term αAn onto the projected code after the ﬁrst step._

**Comment by ShenYujun** [comment]
I think this may be a misunderstanding. `G1(z) = y = Az + b` is a general formulation for GANs. For traditional GANs, like PGGAN, `z` is the Gaussian noise. For style-based GANs, like StyleGAN, `z` denotes the disentangled latent code.

**Comment by cnnlstm** [comment]
> I think this may be a misunderstanding. `G1(z) = y = Az + b` is a general formulation for GANs. For traditional GANs, like PGGAN, `z` is the Gaussian noise. For style-based GANs, like StyleGAN, `z` denotes the disentangled latent code.

Thanks
