### ISSUE TITLE
how to directly use checkpoint from stylegan2-ada-pytorch

### ISSUE THREAD

**Issue by tianyilt** [genforce/sefa#9]
Hi, thanks for your great work and easy to use streamlit app. The current available checkpoint has impressed me  a lot, however, i find it hard to use other checkpoint from nvlab official repositorys such as stylegan2-ada-pytorch. Detail list following:
# different checkpoint type
## genfporce checkpoint
I try to download some checkpoint from 'model zoo', the checkpoint end with `.pth` and load through `torch.load()`
## stylegan2-ada-checkpoint
My trained checkpoint end with `.pkl`. It seems to be saved in nvlab's unique method.
# my effort
- Directly use `torch.load()` to load checkpoint

- Search for some method to convert the `pkl` checkpoint in genforce repository issues. 
But I failed to find a resolution.

**Comment by ShenYujun** [comment]
You only need to figure out how to visit the weight you would like to factorize. No matter what type of checkpoint you are dealing with, loading the parameters as `numpy.ndarray` will be good enough. The key implementation is only with [two lines](https://github.com/genforce/sefa/blob/0d16060208506f5a68df8826bd581a7e0cf0cb4c/utils.py#L190).

**Comment by tianyilt** [comment]
Thanks, I have deployed this algorithm in implicit ae, and it is well to DIY in nvlab's repository.

**Comment by mikkelmedm** [comment]
Hi @tianyilt, did you get this to work?
Have a stylegan2-ada .pkl file that i would like to run as well using Sefa
